### ISSUE TITLE
In data GSM7291623 (mouse_brain_SIMPLE ), error occurs when running SIMPLE-seq data preprocessing process

### ISSUE THREAD

**Issue by shengwei666** [cxzhu/SIMPLE-seq#1]
Dear authors:

 I am currently using the SIMPLE-seq preprocessing pipeline available on GitHub to process the data mentioned in the article, GSE197740 (mESC_SIMPLE, PBMC_SIMPLE, and mouse_brain_SIMPLE). However, this preprocessing pipeline is only applicable for processing paired-end sequencing data. Therefore, I have only processed GSM7291623 (mouse_brain_SIMPLE). **It would be great if you could provide a workflow for processing SIMPLE-seq single-end data.**

**While processing the GSM7291623 (mouse_brain_SIMPLE) data, I encountered some issues.** It would be great if you could help me resolve them. During the **mapping to the genome** step, while using **Bowtie2** for alignment, **I encountered the following error:** 
"Error:ReadSRR24423085.6972:AAATTGCTAG:TTAATACAACTATGTGGTCCAGCGGCCACTATCCCACTCCTATCCAAGGTCGAGGGCCAACATTAGGAAGGCTGCCGCCACCACTGTGAGGGCGCCTGACCATGACCACTGCTTTAGAACAAATGGAAGCACTTGTTTGCAAATTGTCCG:F:,,F:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFF:45:72:04 **has more quality values than read characters.**"  Later, I located this particular read and examined it, **as shown in the following figure.**
![18](https://github.com/cxzhu/SIMPLE-seq/assets/108166408/46947cc5-2840-40e2-9f80-2fbb1effdc5b)
.
![19](https://github.com/cxzhu/SIMPLE-seq/assets/108166408/1a7c7b99-20fd-47d8-9f3a-c3032bfd4526)

With a trial-and-error mindset, I replaced symbols with corresponding letters in the second or third line, and the script ran successfully. However, during the step **"zcat SRR24423085_mapped.sam.gz | samtools sort - -o SRR24423085_mapped_sorted.bam"**, I encountered the following error: **"query name too long,"** as shown in the figure below.
![20](https://github.com/cxzhu/SIMPLE-seq/assets/108166408/50956b20-5a60-44e8-a109-dcc99f72b45c)

**Comment by cxzhu** [comment]
@shengwei666 Thanks for your interest in our dataset!

1. For the mESC and PBMC sample, they are also paired-end reads. However, there might be some incompatible issue between BGI and GEO so the read1 is missing (also the read lengths is incorrect in the GEO): it should be 200+100 for mESC/PBMC sequenced by BGI and 150+150 sequenced by Illumina.

@DongshengBai, please contact GEO to resolve this issue.

- [x] Fix mESC/PBMC GEO record.

2. For the errors you encountered in mouse brain data, this is related to the renaming of read names during GEO compression. I have updated the perl scripts (https://github.com/cxzhu/SIMPLE-seq/blob/main/perlscripts/01.sam2fastq.pl) to fix this issue. I also updated the comments in (https://github.com/cxzhu/SIMPLE-seq/blob/main/shellscripts/01.pre_process_simple_seq_fastq.sh) to highlight the differences in processing mESC/PBMC and brain dataset.

Attached is the jupyter notebook (bash only) in re-processing 100k reads downloaded from the GEO brain dataset. I apologize for the inconvenience! The updated scripts should be working now.
[Test_GEO_download.html.zip](https://github.com/cxzhu/SIMPLE-seq/files/14744095/Test_GEO_download.html.zip)

**Comment by shengwei666** [comment]
Dear Professor Chenxu Zhu,

**Thank you very much for your prompt response and invaluable assistance.** Following the script update you provided, I have successfully completed the SIMPLE-seq data processing for mouse brain sample.

By the way, **I would like to inquire about the approximate time it will take for the GSM5929312 (mESC_SIMPLE) and GSM5929313 (PBMC_SIMPLE) datasets to be corrected and uploaded to the GEO database.** Specifically, my current research might be more interested in obtaining the GSM5929313 (PBMC_SIMPLE) dataset and processing this sample with your SIMPLE-seq data processing pipeline.

Best regards,
Shengwei Li

**Comment by cxzhu** [comment]
Dear @shengwei666, please email @DongshengBai (dbai@nygenome.org) and me (czhu@nygenome.org) to discuss the alternative way for data sharing if fixing GEO takes longer time.
