### ISSUE TITLE
Missing "\t"

### ISSUE THREAD

**Issue by onurcanbektas** [cxzhu/SIMPLE-seq#2]
In here

https://github.com/cxzhu/SIMPLE-seq/blob/4856b326a59960a2c49e28a9b12498ad6ba0f9bd/perlscripts/03.bam2srf.pl#L106

and here

https://github.com/cxzhu/SIMPLE-seq/blob/4856b326a59960a2c49e28a9b12498ad6ba0f9bd/perlscripts/03.bam2srf.pl#L95

you are missing a "\t" after $bc.

**Comment by cxzhu** [comment]
@onurcanbektas Thanks! Fixed them (lines 95, 106, 117) now.
