### ISSUE TITLE
Is this line a mistake?

### ISSUE THREAD

**Issue by onurcanbektas** [cxzhu/SIMPLE-seq#4]
At line https://github.com/cxzhu/SIMPLE-seq/blob/5485b40c32da135169191d1a27d850013fc8fddc/perlscripts/03.bam2srf.pl#L94
to determine whether a cite is methylated, the number of tyrosine is compared to the total number of cytosine + tyrosine. If the fraction if larger than 0.5, then the site is marked as methylated.

But if I understand the method correctly, only unmethylated cites would go under C-to-T conversion. So shouldn't the comparison in that line be less than or equal to mark a position as methylated?

**Comment by cxzhu** [comment]
No, only the methylated/hydromethylated Cs undergo C-to-T conversion. You can find the details in the SIMPLE-seq paper: https://www.nature.com/articles/s41587-024-02148-9
