### ISSUE TITLE
how can we determine which cells from 2i-cultured or serum conditions?

### ISSUE THREAD

**Issue by onurcanbektas** [cxzhu/SIMPLE-seq#6]
In the [data](https://www.ncbi.xyz/geo/query/acc.cgi?acc=GSM5929312), how can we determine which cells from 2i-cultured or serum conditions?

**Comment by cxzhu** [comment]
Relevent to #4. The requested information is available from the publication.

**Comment by onurcanbektas** [comment]
We already looked at the publication but couldn't find it. They is why we are asking. 
We would appreciate if you could point us to.

**Comment by cxzhu** [comment]
thanks again for your intest in our method. these information is listed in "Supplementary_Table2: Metadata of mESC cells.".

**Comment by cxzhu** [comment]
> In the [data](https://www.ncbi.xyz/geo/query/acc.cgi?acc=GSM5929312), how can we determine which cells from 2i-cultured or serum conditions?

Dear @onurcanbektas, in mammalian genome, DNA methylation are typically in CpG dinucleotides.
